extends:
    - "react-app"
plugins:
    - "react"
    - "@typescript-eslint"
    - "react-hooks"
parser: "@typescript-eslint/parser"
parserOptions:
    project: './tsconfig.json'
settings:
    react:
        version: "16.4.1"
globals:
    Feature: true
    Scenario: true
    Data: true
rules:
    no-debugger: ["error"]
    no-console: ["warn"]
    no-restricted-globals: [2, "localStorage", "sessionStorage"]
    no-useless-computed-key: ["off"]
    no-unneeded-ternary: ["warn", {
        "defaultAssignment": false
    }]
    no-confusing-arrow: ["off"] # conflicting with prettier
    jsx-a11y/no-static-element-interactions: ["warn"]
    react/prop-types: ["off"]
    react/require-default-props: ["warn"]
    react/no-unused-prop-types: ["warn"]
    no-unused-vars: "off"
    "@typescript-eslint/no-unused-vars": "warn"
    "@typescript-eslint/no-var-requires": "error"
    "@typescript-eslint/consistent-type-assertions": ["off"]
    react/require-optimization: ["warn"]
    react/no-redundant-should-component-update: ["warn"]
    react/jsx-key: ["warn"]
    react/prefer-stateless-function: ["warn"]
    react/jsx-handler-names: ["warn", {
        "eventHandlerPrefix": "handle",
        "eventHandlerPropPrefix": "on"
    }]
    react-hooks/rules-of-hooks: ["error"]
    react-hooks/exhaustive-deps: ["warn"]
    react/no-direct-mutation-state: ["error"]
    react/no-string-refs: "error"
overrides:
    - files: ["*.js"]
      rules:
          react/jsx-no-literals: ["off"]
    - files: ["*.ts"]
      rules:
          "@typescript-eslint/no-var-requires": ["off"]
